version: '3.3'

volumes:
    mongodb_data:

services:  
    web-service:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=development
            - MONGO_HOST=webservice-mongo-1:29017
        ports:
            - 3333:3333
    mongo:
        image: mongo:latest
        volumes: 
            - mongodb_data:/data/db
        command:  mongod --port 29017
        ports:
            - 29017:29017

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq2
        hostname: rabbitmq
        volumes:
        - /var/lib/rabbitmq
        ports:
        - "5672:5672"
        - "15672:15672"
        env_file:
        - ./.env
            