version: '3.3'

volumes:
    mongodb_data:

services:  
    tree-service:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=development
            - MONGO_HOST=tree_mongo_1:29017
        ports:
            - 3333:3333
    mongo:
        image: mongo:latest
        volumes: 
            - mongodb_data:/data/db
        command:  mongod --port 29017
        ports:
            - 29017:29017
            